### PR TITLE
Adding the missing lib

### PR DESCRIPTION
**Pull request by MohamedMawed**
Adding a missing package
: package org.jetbrains.annotations does not exist
import org.jetbrains.annotations.Nullable;

### CODE REVIEW

**Comment by Sn0wStorm** [comment]
How did you fix the issue with the missing lib?

**Comment by MohamedMawed** [comment]
@Sn0wStorm I added this line into the `android/build.gradle` file and the error passed and beacons get detected correctly 
`implementation 'com.intellij:annotations:+@jar`.

hope it helps

**Comment by Sn0wStorm** [comment]
Ok thank you, I thought you might have found another fix as the merge request is closed now.

**Comment by MohamedMawed** [comment]
this might get fixed in the next releases that's why I closed the PR

**Pull request closed without merging**
