### PR TITLE
Send events through NativeEventEmitter rather than the bridge on iOS.

### PR DESCRIPTION
**Pull request by ashemah**
This is based off the latest RN native modules docs.

I have also updated the ranging.ios.js example.

Note: I am getting an error when running this: 

this._nativeModule.addListener is not a function. 

I have no idea where this is coming from exactly.

### CODE REVIEW

**Comment by MacKentoch** [comment]
Thank you @ashemah 

Reviewing was straight forward, nice job!

- I will have to update documentation and example samples to reflect this new version.
- push it to npm (within this day)

**Comment by ashemah** [comment]
Hi Erwan, can you confirm that it is working properly? I am having issues
with it still and don't want you to push something broken.

I think the issue was that the code is now using the 'next' versions of the
JS platform specific libraries when I thought it was using the old versions.

I am still looking into it but please don't push it to NPM if you are
seeing an issue as well.

**Comment by MacKentoch** [comment]
I will fix it soon.

Right now I can't dedicate time.
It is ok no worry.

**Comment by MacKentoch** [comment]
@ashemah you did a good job 👍  

I fixed [BeaconsDemo project](https://github.com/MacKentoch/react-native-beacons-manager/blob/master/examples/BeaconsDemo/index.ios.js).

```javascript
DeviceEventEmitter.addListener()
// simply becomes (for android and iOS)
Beacons.BeaconsEventEmitter.addListener()
```

I have now another really interesting PR( #45 from @stoneman1) to review and merge (*for android this time*).

So it stays in master and maybe I may create a `v1.1.0` because of breaking changes introduced (*for the good!*).

**Comment by dlindahl** [comment]
You know... now that the event emitter is on the `Beacons` object instead of `DeviceEventEmitter`, it makes it easier to provide a "mock" beacon event emitter for use in the simulator... 🤔

**Comment by MacKentoch** [comment]
Yes @dlindahl .

This is now `mockable` (*not sure this word exists... You know French people love inventing words* 😄).

I just wonder what use case apart from simulating you ranged a beacon or left a region after a timeout?

I would be pleased to read your suggestions

**Pull request merged**
